README.md changes
0chain/s3-migration pull request #86
Opened 2023-08-04 18:48 UTC by hm90121

--added table of contents
-- zus overview
-- added sample migration command syntax
-- added build instructions
-- corrected typos

2023-09-15 13:42 UTC, boddumanohar approved these changes

2023-09-22 18:22 UTC, Kishan-Dhakan requested changes

2023-09-22 18:22 UTC, Kishan-Dhakan commented on README.md
> +# s3-migration - a CLI for migrating AWS S3 bucket to Züs dStorage
`a CLI tool` please

2023-09-22 18:22 UTC, Kishan-Dhakan commented on README.md
> +Global Flags are parameters in s3igration that can be used with any command to override the default configuration supports the following global parameters.
s3migration (spelling)

2023-09-22 18:22 UTC, Kishan-Dhakan commented on README.md
> +However users can specify some prefix to migrate only the files with those prefix. Also if there is name conflict within dStorage file and bucket file use can
Please change to `dStorage file and bucket file users can` (typo in users)

2023-09-26 10:40 UTC, hm90121 commented
applied your suggestions

2023-09-28 08:13 UTC, Kishan-Dhakan approved these changes

2023-09-28 08:13 UTC, merged